### ISSUE TITLE
Contributing links require Google corp SSO in the website

### ISSUE THREAD

**Issue by PragmaTwice** [openxla/community#121]
![image](https://github.com/user-attachments/assets/c72eeee8-18c0-473c-840f-05c8303032e8)

The community contributing links in the website (https://openxla.org) redirect users to the Google internal SSO page (https://login.corp.google.com), 
which is quite confusing, even make users to think that maybe only Googlers can contribute to ***Open***XLA.

The correct URL seems to be https://openxla.org/xla/contributing.

**Comment by ghpvnist** [comment]
Thank you for flagging this! This has now been fixed.
